// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelChat() {
  return window['go']['main']['App']['CancelChat']();
}

export function CancelDeviceLogin() {
  return window['go']['main']['App']['CancelDeviceLogin']();
}

export function GetActiveRequest() {
  return window['go']['main']['App']['GetActiveRequest']();
}

export function GetBootstrap() {
  return window['go']['main']['App']['GetBootstrap']();
}

export function GetDeviceLoginState() {
  return window['go']['main']['App']['GetDeviceLoginState']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetUsage() {
  return window['go']['main']['App']['GetUsage']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function RenameAccount(arg1, arg2) {
  return window['go']['main']['App']['RenameAccount'](arg1, arg2);
}

export function SendChat(arg1) {
  return window['go']['main']['App']['SendChat'](arg1);
}

export function SetActiveAccount(arg1) {
  return window['go']['main']['App']['SetActiveAccount'](arg1);
}

export function StartDeviceLogin() {
  return window['go']['main']['App']['StartDeviceLogin']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
